version: "3.9"

services:
  api:
    image: noticc/churn-api:latest     
    container_name: churn_api
    ports:
      - "8000:8000"
    networks:
      - churn-net

  streamlit:
    image: noticc/churn-ui:latest      
    container_name: churn_ui
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - churn-net

networks:
  churn-net:
    driver: bridge
